name: weight_track_app
description: The weight track app, now written in flutter
version: 1.2.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^2.2.1

dependencies:
  custom_navigator:
  google_fonts:
  sqflite: ^1.0.0
  path_provider: ^1.4.0
  shared_preferences:
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  localstorage: ^3.0.6
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
  
